name: dev
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^7.0.0
  angular_forms: ^4.0.0
  sass_builder: ^2.1.3

dev_dependencies:
  angular_test: any
  build_runner: any
  build_test: any
  build_web_compilers: any
